# Generated by Django 5.0.1 on 2026-05-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discovery_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("friend", "Amigo o colega"),
                    ("search_engine", "Buscadores"),
                    ("social_media", "Redes sociales"),
                    ("website", "Sitio web o blog"),
                    ("event", "Evento o showcase"),
                    ("other", "Otro"),
                ],
                help_text="¿Cómo descubriste Pulsar?",
                max_length=20,
            ),
        ),
    ]
