# Generated by Django 5.2.11 on 2026-05-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_discovery_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_partner_active',
            field=models.BooleanField(default=False, help_text='Si el usuario tiene el rol Aliado activo (puede ser además de Talento/Cliente)'),
        ),
        migrations.AddField(
            model_name='user',
            name='partner_offers',
            field=models.JSONField(blank=True, default=list, help_text='Qué ofrece el Aliado. Valores: "referral" (trae clientes), "packs" (renta producción), "venue" (espacio físico)'),
        ),
    ]
