# Generated by Django 5.2.11 on 2026-07-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_seen_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='Panamá', max_length=50, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='discovery_source',
            field=models.CharField(blank=True, choices=[('friend', 'Amigo o colega'), ('search_engine', 'Buscadores'), ('social_media', 'Redes sociales'), ('website', 'Sitio web o blog'), ('event', 'Evento o showcase'), ('other', 'Otro')], help_text='¿Cómo descubriste Pulsar?', max_length=20, verbose_name='¿Cómo nos conoció?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_partner_active',
            field=models.BooleanField(default=False, help_text='Si el usuario tiene el rol Aliado activo (puede ser además de Talento/Cliente)', verbose_name='Rol Aliado activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verificado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_offers',
            field=models.JSONField(blank=True, default=list, help_text='Qué ofrece el Aliado. Valores: "referral" (trae clientes), "packs" (renta producción), "venue" (espacio físico)', verbose_name='Ofertas del Aliado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('talent', 'Talento'), ('client', 'Cliente'), ('admin', 'Administrador'), ('partner', 'Aliado')], default='client', max_length=10, verbose_name='Rol principal'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
    ]
