# Generated by Django 5.2.11 on 2026-04-16 20:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('directa', 'Directa'), ('partner', 'Partner')], default='directa', max_length=10)),
                ('event_type', models.CharField(choices=[('wedding', 'Boda'), ('corporate', 'Evento Corporativo'), ('birthday', 'Cumpleaños'), ('graduation', 'Graduación'), ('festival', 'Festival'), ('club', 'Club/Discoteca'), ('private', 'Fiesta Privada'), ('anniversary', 'Aniversario'), ('other', 'Otro')], max_length=20)),
                ('event_name', models.CharField(blank=True, max_length=200)),
                ('event_date', models.DateField()),
                ('event_time_start', models.TimeField()),
                ('event_time_end', models.TimeField()),
                ('event_duration_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Duración del servicio en horas', max_digits=5, null=True)),
                ('event_location', models.CharField(max_length=300)),
                ('event_city', models.CharField(blank=True, max_length=100)),
                ('guest_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, help_text='Detalles y requerimientos')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto del cliente', max_digits=10, null=True)),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Precio estimado por el sistema (tarifa/hora × duración)', max_digits=10, null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio final propuesto por el talento', max_digits=10, null=True)),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Porcentaje requerido como depósito', max_digits=5)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total pagado hasta ahora', max_digits=10)),
                ('status', models.CharField(choices=[('solicitud_enviada', 'Solicitud Enviada'), ('pendiente_respuesta', 'Pendiente de Respuesta'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('pendiente_pago', 'Pendiente de Pago'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='solicitud_enviada', max_length=20)),
                ('talent_notes', models.TextField(blank=True, help_text='Notas del talento sobre la cotización')),
                ('client_notes', models.TextField(blank=True, help_text='Notas adicionales del cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bookings', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, help_text='Partner que gestionó esta reserva', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_bookings', to=settings.AUTH_USER_MODEL)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='talents.talentprofile')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('file_url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bookings.booking')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_request', 'Nueva Solicitud'), ('request_accepted', 'Solicitud Aceptada'), ('request_rejected', 'Solicitud Rechazada'), ('payment_received', 'Pago Recibido'), ('booking_confirmed', 'Reserva Confirmada'), ('booking_completed', 'Reserva Completada'), ('new_review', 'Nueva Reseña'), ('new_message', 'Nuevo Mensaje'), ('reminder', 'Recordatorio'), ('system', 'Sistema')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='URL interna', max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('deposit', 'Abono/Depósito'), ('full', 'Pago Total'), ('balance', 'Saldo Restante')], max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=10)),
                ('payment_method', models.CharField(choices=[('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('paypal', 'PayPal'), ('cash', 'Efectivo'), ('other', 'Otro')], default='card', max_length=10)),
                ('commission_showroots', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Comisión para ShowRoots', max_digits=10)),
                ('commission_partner', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Comisión para el Partner (si aplica)', max_digits=10)),
                ('talent_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto neto para el talento', max_digits=10)),
                ('transaction_ref', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='talents.talentprofile')),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
