# Generated by Django 5.2.11 on 2026-04-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_final_email',
            field=models.EmailField(blank=True, help_text='Email del cliente final', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_final_name',
            field=models.CharField(blank=True, help_text='Nombre del cliente final (si es reserva por Partner)', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_final_phone',
            field=models.CharField(blank=True, help_text='Telefono del cliente final', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='event_indoor',
            field=models.BooleanField(default=True, help_text='True=Interior, False=Exterior'),
        ),
        migrations.AddField(
            model_name='booking',
            name='genre_preference',
            field=models.CharField(blank=True, help_text='Genero o ambiente deseado', max_length=100),
        ),
    ]
