# Generated by Django 5.2.11 on 2026-04-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_client_final_email_booking_client_final_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_services',
            field=models.JSONField(blank=True, default=list, help_text='Servicios adicionales de producción seleccionados'),
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_services_notes',
            field=models.TextField(blank=True, help_text='Notas sobre servicios de producción adicionales'),
        ),
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de expiración automática de la solicitud', null=True),
        ),
    ]
