# Generated by Django 5.2.11 on 2026-04-19 13:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_additional_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1500'), help_text='Comisión de la plataforma (ej: 0.15 = 15%)', max_digits=5)),
                ('partner_commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.3000'), help_text='Comisión del partner sobre la comisión de la plataforma (ej: 0.30 = 30%)', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Plataforma',
                'verbose_name_plural': 'Configuración de Plataforma',
                'db_table': 'platform_config',
            },
        ),
    ]
