# Generated by Django 5.2.11 on 2026-04-21 20:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_add_platform_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformconfig',
            name='platform_commission_rate',
        ),
        migrations.AddField(
            model_name='booking',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee de gestión y garantía cobrado al cliente', max_digits=10),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='premium_commission_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1500'), help_text='Comisión para talentos Premium (ej: 0.15 = 15%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='service_fee_large',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Fee para eventos grandes ($800+)', max_digits=8),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='service_fee_medium',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Fee para eventos medianos ($400–$800)', max_digits=8),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='service_fee_mode',
            field=models.CharField(choices=[('percentage', 'Porcentaje del total'), ('tiered', 'Escalonado por monto')], default='percentage', help_text='Modo de cálculo del fee: porcentaje o escalonado', max_length=10),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='service_fee_name',
            field=models.CharField(default='Gestión y garantía', help_text='Nombre del fee que se muestra al cliente', max_length=100),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='service_fee_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='Fee como porcentaje del total (ej: 0.05 = 5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='service_fee_small',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Fee para eventos pequeños ($150–$400)', max_digits=8),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='standard_commission_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.2000'), help_text='Comisión para talentos Standard (ej: 0.20 = 20%)', max_digits=5),
        ),
    ]
