# Generated by Django 5.2.11 on 2026-05-13 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_platformconfig_platform_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating_communication',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Comunicación pre-evento', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_crowd_reading',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Lectura del público', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_music_selection',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Selección musical', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_punctuality',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Puntualidad', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_technique',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Técnica', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
