# Generated by Django 5.2.11 on 2026-05-13 22:24

import django.db.models.deletion
import secrets, string
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_booking_codes(apps, schema_editor):
    """Generate unique booking_code for existing bookings."""
    Booking = apps.get_model('bookings', 'Booking')
    used = set()
    for b in Booking.objects.all():
        if b.booking_code:
            used.add(b.booking_code)
            continue
        # Generate based on created_at
        year = b.created_at.year if b.created_at else 2026
        month = b.created_at.month if b.created_at else 1
        while True:
            rand = ''.join(secrets.choice(string.ascii_uppercase + string.digits) for _ in range(4))
            code = f"PUL-{year}-{month:02d}-{rand}"
            if code not in used:
                used.add(code)
                break
        b.booking_code = code
        b.save(update_fields=['booking_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_review_rating_communication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: añadir el campo SIN unique todavía
        migrations.AddField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, help_text='Código público corto para mostrar al cliente', max_length=24),
        ),
        # Step 2: backfill códigos en bookings existentes
        migrations.RunPython(backfill_booking_codes, reverse_code=migrations.RunPython.noop),
        # Step 3: ahora sí, aplicar unique
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, help_text='Código público corto para mostrar al cliente', max_length=24, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ITBMS 7% calculado sobre el total', max_digits=10),
        ),
        migrations.AddField(
            model_name='message',
            name='flagged',
            field=models.BooleanField(default=False, help_text='True si el scanner anti-disinter detectó intento de contacto fuera de plataforma'),
        ),
        migrations.AddField(
            model_name='message',
            name='flagged_categories',
            field=models.JSONField(blank=True, default=list, help_text='Categorías detectadas (phone, email, whatsapp, etc.)'),
        ),
        migrations.AddField(
            model_name='message',
            name='raw_content',
            field=models.TextField(blank=True, help_text='Texto original antes del scanner anti-desintermediación'),
        ),
        migrations.CreateModel(
            name='ClientCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('review_reward', 'Recompensa por dejar reseña'), ('referral', 'Referencia'), ('refund', 'Reembolso'), ('promo', 'Promoción'), ('manual', 'Ajuste manual')], default='manual', max_length=20)),
                ('used', models.BooleanField(default=False, help_text='Si el crédito ya fue redimido')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_generated', to='bookings.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
                ('used_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_redeemed', to='bookings.booking')),
            ],
            options={
                'db_table': 'client_credits',
                'ordering': ['-created_at'],
            },
        ),
    ]
