# Generated by Django 5.2.11 on 2026-05-13 22:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_booking_code_booking_tax_amount_and_more'),
        ('talents', '0004_talentprofile_equipment_brings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='auto_promote_min_events',
            field=models.PositiveIntegerField(default=10, help_text='Eventos mínimos completados para promoción auto a Pro'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='auto_promote_min_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.50'), help_text='Rating promedio mínimo para promoción a Pro', max_digits=3),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='cancel_full_refund_days',
            field=models.PositiveIntegerField(default=7, help_text='Días antes del evento con reembolso 100%'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='cancel_partial_refund_days',
            field=models.PositiveIntegerField(default=2, help_text='Días antes del evento con reembolso 50%'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='cancel_partial_refund_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Porcentaje de reembolso en el rango parcial (ej: 0.50 = 50%)', max_digits=4),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='high_season_months',
            field=models.JSONField(blank=True, default=list, help_text='Meses de alta temporada (1-12). Ej: [11, 12, 1] = nov-dic-ene'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='high_season_surcharge_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.15'), help_text='Sobreprecio en alta temporada para Premium (ej: 0.15 = +15%)', max_digits=4),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='pro_commission_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1500'), help_text='Comisión Pro (ej: 0.15 = 15%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='review',
            name='response',
            field=models.TextField(blank=True, help_text='Respuesta pública del talento a la reseña (sólo Premium)'),
        ),
        migrations.AddField(
            model_name='review',
            name='response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_request', 'Nueva Solicitud'), ('request_accepted', 'Solicitud Aceptada'), ('request_rejected', 'Solicitud Rechazada'), ('payment_received', 'Pago Recibido'), ('booking_confirmed', 'Reserva Confirmada'), ('booking_completed', 'Reserva Completada'), ('new_review', 'Nueva Reseña'), ('new_message', 'Nuevo Mensaje'), ('reminder', 'Recordatorio'), ('system', 'Sistema'), ('tier_upgrade', 'Subida de Tier'), ('premium_invitation', 'Invitación Premium'), ('flagged_warning', 'Advertencia de Mensaje')], max_length=20),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='premium_commission_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1200'), help_text='Comisión Premium (ej: 0.12 = 12%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='standard_commission_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.2200'), help_text='Comisión Standard (ej: 0.22 = 22%)', max_digits=5),
        ),
        migrations.CreateModel(
            name='PremiumInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('declined', 'Rechazada'), ('expired', 'Expirada'), ('revoked', 'Revocada')], default='pending', max_length=12)),
                ('message', models.TextField(blank=True, help_text='Mensaje opcional al talento explicando la invitación')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, help_text='Admin que envió la invitación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_invitations', to='talents.talentprofile')),
            ],
            options={
                'db_table': 'premium_invitations',
                'ordering': ['-sent_at'],
            },
        ),
    ]
