# Generated by Django 5.2.11 on 2026-05-13 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_platformconfig_auto_promote_min_events_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('solicitud_enviada', 'Solicitud Enviada'), ('pendiente_respuesta', 'Pendiente de Respuesta'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('pendiente_pago', 'Pendiente de Pago'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('en_disputa', 'En Disputa')], default='solicitud_enviada', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('talent_approve', 'Aprobar talento'), ('talent_reject', 'Rechazar talento'), ('booking_refund', 'Emitir reembolso'), ('dispute_resolve', 'Resolver disputa'), ('premium_invite', 'Invitar a Premium'), ('user_ban', 'Banear usuario'), ('user_warn', 'Advertir usuario (flagged)'), ('config_change', 'Cambiar config plataforma'), ('other', 'Otra')], max_length=30)),
                ('target_type', models.CharField(blank=True, help_text='Tipo del objeto afectado (booking, talent, user, etc.)', max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('no_show', 'No se presentó'), ('late', 'Llegó muy tarde'), ('poor_service', 'Servicio deficiente'), ('different_artist', 'Vino un artista distinto'), ('equipment_failure', 'Fallas con el equipo'), ('other', 'Otro')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('investigating', 'En revisión'), ('resolved_refund', 'Resuelta — reembolso'), ('resolved_paid', 'Resuelta — pago al talento'), ('resolved_split', 'Resuelta — repartido'), ('closed', 'Cerrada sin acción')], default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto reembolsado al cliente', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='bookings.booking')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_reported', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disputes',
                'ordering': ['-created_at'],
            },
        ),
    ]
