# Generated by Django 5.2.11 on 2026-05-15 00:44

from decimal import Decimal
from django.db import migrations, models


def update_existing_standard_rate(apps, schema_editor):
    """Actualiza el PlatformConfig existente al nuevo valor 20% si seguía en 22%."""
    PlatformConfig = apps.get_model('bookings', 'PlatformConfig')
    PlatformConfig.objects.filter(standard_commission_rate=Decimal('0.2200')).update(
        standard_commission_rate=Decimal('0.2000')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_status_auditlog_dispute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconfig',
            name='standard_commission_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.2000'), help_text='Comisión Standard (ej: 0.20 = 20%)', max_digits=5),
        ),
        migrations.RunPython(update_existing_standard_rate, reverse_code=migrations.RunPython.noop),
    ]
