# Generated by Django 5.2.11 on 2026-05-24 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_update_standard_commission_to_20'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProductionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.JSONField(blank=True, default=list, help_text='Lista de categorías ofrecidas (slugs). Ej: ["sound", "lights", "mics"]')),
                ('main_city', models.CharField(blank=True, max_length=100)),
                ('coverage_radius_km', models.PositiveIntegerField(default=50, help_text='Radio de cobertura en km')),
                ('travel_fee_extra', models.DecimalField(blank=True, decimal_places=2, help_text='Cargo extra fuera del radio de cobertura', max_digits=8, null=True)),
                ('max_simultaneous_events', models.PositiveIntegerField(default=1, help_text='Máximo de eventos simultáneos (por noche)')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales del partner')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente de verificación'), ('verified', 'Verificado'), ('rejected', 'Rechazado')], default='draft', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('onboarding_step', models.PositiveSmallIntegerField(default=1, help_text='Paso actual del wizard (1-4). 4 = completado y enviado a verificación.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_profiles_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_production_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerProductionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='partner/equipment/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bookings.partnerproductionprofile')),
            ],
            options={
                'db_table': 'partner_production_photos',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
