# Generated by Django 5.2.11 on 2026-05-24 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_partnerproductionprofile_partnerproductionphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('sound', 'Sonido'), ('lights', 'Iluminación'), ('screens', 'Pantallas'), ('mics', 'Microfonía'), ('dj_booth', 'DJ Booth'), ('fx', 'FX / Especiales')], help_text='Categoría de equipo: sound, lights, screens, mics, dj_booth, fx', max_length=20)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('event_size', models.CharField(choices=[('small', 'Pequeño (<80)'), ('medium', 'Mediano (80-300)'), ('large', 'Grande (300+)')], default='medium', max_length=10)),
                ('equipment_items', models.JSONField(blank=True, default=list, help_text='Items incluidos. Ej: ["2x QSC KW153", "Mixer Pioneer DJM-A9", ...]')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('includes_technician', models.BooleanField(default=True)),
                ('includes_setup', models.BooleanField(default=True)),
                ('setup_hours_before', models.PositiveSmallIntegerField(default=2)),
                ('available_days', models.JSONField(blank=True, default=list, help_text='Días disponibles. Ej: ["mon","tue","wed","thu","fri","sat"]')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='partner/packs/')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('paused', 'Pausado')], default='draft', max_length=10)),
                ('rentals_count', models.PositiveIntegerField(default=0)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='bookings.partnerproductionprofile')),
            ],
            options={
                'db_table': 'production_packs',
                'ordering': ['-rentals_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_packs', to='bookings.booking')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_uses', to='bookings.productionpack')),
            ],
            options={
                'db_table': 'booking_packs',
                'ordering': ['created_at'],
                'unique_together': {('booking', 'pack')},
            },
        ),
    ]
