# Generated by Django 5.2.11 on 2026-05-25 00:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_productionpack_bookingpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='pack_commission_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.2000'), help_text='Comisión Pulsar sobre packs de producción (ej: 0.20 = 20%)', max_digits=5),
        ),
    ]
