# Generated by Django 5.2.11 on 2026-05-25 00:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_platformconfig_pack_commission_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Descuento sobre la suma de precios individuales (ej: 15.00 = 15%)', max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('paused', 'Pausado')], default='draft', max_length=10)),
                ('rentals_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packs', models.ManyToManyField(related_name='bundles', to='bookings.productionpack')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='bookings.partnerproductionprofile')),
            ],
            options={
                'db_table': 'pack_bundles',
                'ordering': ['-rentals_count', '-created_at'],
            },
        ),
    ]
