# Generated by Django 5.2.11 on 2026-07-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_productionpack_includes_dj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Registro de auditoría', 'verbose_name_plural': 'Registros de auditoría'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='bookingpack',
            options={'ordering': ['created_at'], 'verbose_name': 'Pack en reserva', 'verbose_name_plural': 'Packs en reservas'},
        ),
        migrations.AlterModelOptions(
            name='clientcredit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Crédito de cliente', 'verbose_name_plural': 'Créditos de cliente'},
        ),
        migrations.AlterModelOptions(
            name='dispute',
            options={'ordering': ['-created_at'], 'verbose_name': 'Disputa', 'verbose_name_plural': 'Disputas'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='packbundle',
            options={'ordering': ['-rentals_count', '-created_at'], 'verbose_name': 'Combo de packs', 'verbose_name_plural': 'Combos de packs'},
        ),
        migrations.AlterModelOptions(
            name='partnerproductionphoto',
            options={'ordering': ['order', 'uploaded_at'], 'verbose_name': 'Foto de equipo (Aliado)', 'verbose_name_plural': 'Fotos de equipo (Aliados)'},
        ),
        migrations.AlterModelOptions(
            name='partnerproductionprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Perfil de producción (Aliado)', 'verbose_name_plural': 'Perfiles de producción (Aliados)'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='premiuminvitation',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Invitación a Premium', 'verbose_name_plural': 'Invitaciones a Premium'},
        ),
        migrations.AlterModelOptions(
            name='productionpack',
            options={'ordering': ['-rentals_count', '-created_at'], 'verbose_name': 'Pack de producción', 'verbose_name_plural': 'Packs de producción'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, db_index=True, help_text='Código público corto para mostrar al cliente', max_length=24, unique=True),
        ),
    ]
