# Generated by Django 5.2.11 on 2026-07-07 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_alter_auditlog_options_alter_booking_options_and_more'),
        ('talents', '0008_alter_availability_options_alter_genre_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_request', 'Nueva Solicitud'), ('request_accepted', 'Solicitud Aceptada'), ('request_rejected', 'Solicitud Rechazada'), ('payment_received', 'Pago Recibido'), ('booking_confirmed', 'Reserva Confirmada'), ('booking_completed', 'Reserva Completada'), ('new_review', 'Nueva Reseña'), ('new_message', 'Nuevo Mensaje'), ('reminder', 'Recordatorio'), ('system', 'Sistema'), ('tier_upgrade', 'Subida de Tier'), ('premium_invitation', 'Invitación Premium'), ('flagged_warning', 'Advertencia de Mensaje'), ('open_gig_available', 'Solicitud Abierta Disponible'), ('open_gig_offer_received', 'Nueva Oferta Recibida'), ('open_gig_offer_accepted', 'Oferta Aceptada'), ('open_gig_offer_rejected', 'Oferta Rechazada'), ('open_gig_expired', 'Solicitud Expirada')], max_length=32),
        ),
        migrations.CreateModel(
            name='OpenGigRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('wedding', 'Boda'), ('corporate', 'Evento Corporativo'), ('birthday', 'Cumpleaños'), ('graduation', 'Graduación'), ('festival', 'Festival'), ('club', 'Club/Discoteca'), ('private', 'Fiesta Privada'), ('anniversary', 'Aniversario'), ('other', 'Otro')], max_length=20)),
                ('event_name', models.CharField(blank=True, max_length=200)),
                ('event_date', models.DateField()),
                ('event_time_start', models.TimeField()),
                ('event_time_end', models.TimeField()),
                ('event_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('event_location', models.CharField(max_length=300)),
                ('event_city', models.CharField(blank=True, max_length=100)),
                ('event_indoor', models.BooleanField(default=True)),
                ('guest_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('genre_preference', models.CharField(blank=True, max_length=100)),
                ('additional_services', models.JSONField(blank=True, default=list)),
                ('additional_services_notes', models.TextField(blank=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('visible_to_tier', models.CharField(choices=[('premium', 'Solo Premium'), ('pro', 'Premium + Pro'), ('all', 'Todos')], default='premium', help_text='Hasta qué tier ven la solicitud actualmente', max_length=10)),
                ('notify_pro_at', models.DateTimeField(blank=True, help_text='Momento en que se debe notificar a los Pro', null=True)),
                ('notify_standard_at', models.DateTimeField(blank=True, help_text='Momento en que se debe notificar a los Standard', null=True)),
                ('pro_notified_at', models.DateTimeField(blank=True, null=True)),
                ('standard_notified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('assigned', 'Asignada'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='open', max_length=12)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiración automática si no se acepta oferta', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_booking', models.ForeignKey(blank=True, help_text='Booking creado cuando se aceptó una oferta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_gig_source', to='bookings.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_gig_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud abierta',
                'verbose_name_plural': 'Solicitudes abiertas',
                'db_table': 'open_gig_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GigOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True, help_text='Mensaje del DJ al cliente')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('withdrawn', 'Retirada')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_offers', to='talents.talentprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='bookings.opengigrequest')),
            ],
            options={
                'verbose_name': 'Oferta de DJ',
                'verbose_name_plural': 'Ofertas de DJ',
                'db_table': 'gig_offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='opengigrequest',
            index=models.Index(fields=['status', 'visible_to_tier'], name='open_gig_re_status_810301_idx'),
        ),
        migrations.AddIndex(
            model_name='opengigrequest',
            index=models.Index(fields=['status', 'expires_at'], name='open_gig_re_status_813338_idx'),
        ),
        migrations.AddConstraint(
            model_name='gigoffer',
            constraint=models.UniqueConstraint(fields=('request', 'talent'), name='unique_offer_per_talent'),
        ),
    ]
