# Generated by Django 5.2.11 on 2026-07-07 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_alter_notification_notification_type_opengigrequest_and_more'),
        ('talents', '0008_alter_availability_options_alter_genre_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gigoffer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Oferta', 'verbose_name_plural': 'Ofertas'},
        ),
        migrations.RemoveConstraint(
            model_name='gigoffer',
            name='unique_offer_per_talent',
        ),
        migrations.AddField(
            model_name='gigoffer',
            name='covers_item',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='gigoffer',
            name='offer_kind',
            field=models.CharField(choices=[('dj', 'DJ'), ('pack', 'Pack de producción')], default='dj', max_length=6),
        ),
        migrations.AddField(
            model_name='gigoffer',
            name='pack',
            field=models.ForeignKey(blank=True, help_text='Pack ofrecido por el aliado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bookings.productionpack'),
        ),
        migrations.AddField(
            model_name='gigoffer',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Usuario Aliado que oferta un pack', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_gig_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opengigrequest',
            name='requested_items',
            field=models.JSONField(blank=True, default=list, help_text='Lista de items solicitados: dj, sound, lights, booth, screens, other'),
        ),
        migrations.AlterField(
            model_name='gigoffer',
            name='message',
            field=models.TextField(blank=True, help_text='Mensaje para el cliente'),
        ),
        migrations.AlterField(
            model_name='gigoffer',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gig_offers', to='talents.talentprofile'),
        ),
        migrations.AddConstraint(
            model_name='gigoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('talent__isnull', False)), fields=('request', 'talent'), name='unique_offer_per_talent'),
        ),
    ]
