# Generated by Django 5.2.11 on 2026-04-16 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji icon', max_length=10)),
            ],
            options={
                'db_table': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent_type', models.CharField(choices=[('dj', 'DJ'), ('musician', 'Músico'), ('band', 'Banda')], max_length=10)),
                ('talent_level', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='standard', help_text='Nivel del talento: standard o premium', max_length=10)),
                ('stage_name', models.CharField(help_text='Nombre artístico', max_length=100)),
                ('tagline', models.CharField(blank=True, help_text='Frase corta descriptiva', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa por hora (USD)', max_digits=10, null=True)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_currency', models.CharField(default='USD', max_length=3)),
                ('equipment_own', models.BooleanField(default=False, help_text='¿Tiene equipo propio?')),
                ('equipment_description', models.TextField(blank=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='talents/covers/')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Venezuela', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin debe aprobar antes de que sea visible')),
                ('is_available', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('soundcloud', models.URLField(blank=True)),
                ('mixcloud', models.URLField(blank=True)),
                ('spotify', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='talents', to='talents.genre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'talent_profiles',
                'ordering': [models.Case(models.When(talent_level='premium', then=0), default=1, output_field=models.IntegerField()), '-is_featured', '-rating_avg', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TalentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Foto'), ('video', 'Video'), ('audio', 'Audio'), ('link', 'Link')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='talents/media/')),
                ('url', models.URLField(blank=True, help_text='YouTube, SoundCloud, Mixcloud URL')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='talents/thumbnails/')),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='talents.talentprofile')),
            ],
            options={
                'db_table': 'talent_media',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TalentExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='talents/experience/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='talents.talentprofile')),
            ],
            options={
                'db_table': 'talent_experiences',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('blocked', 'Bloqueado'), ('booked', 'Reservado')], default='available', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='talents.talentprofile')),
            ],
            options={
                'db_table': 'talent_availability',
                'ordering': ['date', 'time_start'],
                'unique_together': {('talent', 'date')},
            },
        ),
    ]
