# Generated by Django 5.0.1 on 2026-05-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentprofile",
            name="coverage_radius_km",
            field=models.PositiveIntegerField(
                default=50, help_text="Radio de cobertura en km desde su ubicación"
            ),
        ),
        migrations.AddField(
            model_name="talentprofile",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("beginner", "Principiante"),
                    ("semi_professional", "Semiprofesional"),
                    ("professional", "Profesional"),
                    ("expert", "Experto"),
                ],
                default="beginner",
                help_text="Nivel de experiencia del talento",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="talentprofile",
            name="onboarding_completed",
            field=models.BooleanField(
                default=False,
                help_text="Si el talento completó el wizard de onboarding",
            ),
        ),
    ]
