# Generated by Django 5.2.11 on 2026-05-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0002_talentprofile_coverage_radius_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='mood_tags',
            field=models.JSONField(blank=True, default=list, help_text='Lista de moods/vibes (ej: ["Boda elegante", "After party", "Cocktail formal"])'),
        ),
    ]
