# Generated by Django 5.2.11 on 2026-05-13 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0003_talentprofile_mood_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='equipment_brings',
            field=models.JSONField(blank=True, default=list, help_text='Equipamiento que el talento trae (ej: ["2x CDJ-3000", "Mixer DJM-A9", "Auriculares"])'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='equipment_not_included',
            field=models.JSONField(blank=True, default=list, help_text='Equipamiento NO incluido (ej: ["Sonido +80 personas", "Luces", "Pantallas"])'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='event_types',
            field=models.JSONField(blank=True, default=list, help_text='Tipos de eventos que cubre (slugs: wedding, corporate, birthday, cocktail, club, launch)'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='Idiomas en los que puede hacer MC (ej: ["Español", "Inglés"])'),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='talent_level',
            field=models.CharField(choices=[('standard', 'Standard'), ('pro', 'Pro'), ('premium', 'Premium')], default='standard', help_text='Nivel del talento: standard o premium', max_length=10),
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_label', models.CharField(blank=True, help_text='Texto alternativo cuando no hay precio fijo (ej: "Cotizar")', max_length=40)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Duración en horas (ej: 4.0)', max_digits=4, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('included_items', models.JSONField(blank=True, default=list, help_text='Items incluidos (ej: ["DJ + sonido básico", "Micrófono", "Setlist"])')),
                ('is_featured', models.BooleanField(default=False, help_text='Marcar como "POPULAR" en el perfil')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='talents.talentprofile')),
            ],
            options={
                'db_table': 'talent_packs',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='TalentFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='talents.talentprofile')),
            ],
            options={
                'db_table': 'talent_faqs',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
