# Generated by Django 5.2.11 on 2026-05-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0004_talentprofile_equipment_brings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='service_zones',
            field=models.JSONField(blank=True, default=list, help_text='Zonas/barrios específicos de cobertura (ej: ["Casco Antiguo", "Costa del Este", "Coronado"])'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='travel_fee_extra',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cargo adicional por traslado fuera del área de cobertura', max_digits=8, null=True),
        ),
    ]
