# Generated by Django 5.2.11 on 2026-05-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0005_talentprofile_service_zones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='tiktok',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
