# Generated by Django 5.2.11 on 2026-05-25 00:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0006_talentprofile_tiktok'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='recommended_partners',
            field=models.ManyToManyField(blank=True, help_text='Aliados de producción recomendados por este DJ (aparecen primero en su booking flow)', related_name='recommended_by_talents', to=settings.AUTH_USER_MODEL),
        ),
    ]
