# Generated by Django 5.2.11 on 2026-07-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0007_talentprofile_recommended_partners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'time_start'], 'verbose_name': 'Disponibilidad', 'verbose_name_plural': 'Disponibilidades'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Género musical', 'verbose_name_plural': 'Géneros musicales'},
        ),
        migrations.AlterModelOptions(
            name='pack',
            options={'ordering': ['order', 'price'], 'verbose_name': 'Paquete del talento', 'verbose_name_plural': 'Paquetes del talento'},
        ),
        migrations.AlterModelOptions(
            name='talentexperience',
            options={'ordering': ['-date'], 'verbose_name': 'Experiencia (evento pasado)', 'verbose_name_plural': 'Experiencias (eventos pasados)'},
        ),
        migrations.AlterModelOptions(
            name='talentfaq',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'FAQ del talento', 'verbose_name_plural': 'FAQs del talento'},
        ),
        migrations.AlterModelOptions(
            name='talentmedia',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Media del talento', 'verbose_name_plural': 'Media del talento'},
        ),
        migrations.AlterModelOptions(
            name='talentprofile',
            options={'ordering': [models.Case(models.When(talent_level='premium', then=0), default=1, output_field=models.IntegerField()), '-is_featured', '-rating_avg', '-created_at'], 'verbose_name': 'Perfil de talento', 'verbose_name_plural': 'Perfiles de talento'},
        ),
    ]
