# Generated by Django 5.2.11 on 2026-07-03 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0016_alter_auditlog_options_alter_booking_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_kind', models.CharField(choices=[('talent', 'DJ / Talento'), ('partner', 'Aliado de Producción')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'En proceso'), ('paid', 'Pagado'), ('on_hold', 'En espera'), ('cancelled', 'Cancelado')], default='pending', max_length=12)),
                ('method', models.CharField(blank=True, choices=[('bank_transfer', 'Transferencia bancaria'), ('yappy', 'Yappy'), ('cash', 'Efectivo'), ('other', 'Otro')], max_length=15)),
                ('reference', models.CharField(blank=True, help_text='Número de transferencia / referencia bancaria del pago', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin que registró el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payouts (a DJs/Aliados)',
                'db_table': 'payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaguelofacilTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_type', models.CharField(choices=[('deposit', 'Abono/Depósito'), ('full', 'Pago Total'), ('balance', 'Saldo Restante')], default='full', max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('initiated', 'Iniciada'), ('processing', 'Procesando'), ('approved', 'Aprobada'), ('declined', 'Rechazada'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada'), ('error', 'Error')], default='initiated', max_length=15)),
                ('internal_reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('paguelofacil_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('paguelofacil_auth_code', models.CharField(blank=True, max_length=64)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('webhook_payloads', models.JSONField(blank=True, default=list)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paguelofacil_transactions', to='bookings.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paguelofacil_transactions', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, help_text='El Payment del booking creado al aprobarse esta transacción.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paguelofacil_tx', to='bookings.payment')),
            ],
            options={
                'verbose_name': 'Transacción Paguelofacil',
                'verbose_name_plural': 'Transacciones Paguelofacil',
                'db_table': 'paguelofacil_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='paguelofaci_status_f2f9a6_idx'), models.Index(fields=['booking', 'status'], name='paguelofaci_booking_96df4b_idx')],
            },
        ),
    ]
