# Generated by Django 5.2.11 on 2026-04-15 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('venue_type', models.CharField(choices=[('salon', 'Salón de Eventos'), ('hotel', 'Hotel'), ('restaurant', 'Restaurante'), ('club', 'Club/Discoteca'), ('outdoor', 'Al Aire Libre'), ('beach', 'Playa'), ('rooftop', 'Rooftop/Terraza'), ('hacienda', 'Hacienda/Finca'), ('other', 'Otro')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Venezuela', max_length=50)),
                ('capacity_min', models.PositiveIntegerField(default=0)),
                ('capacity_max', models.PositiveIntegerField(default=0)),
                ('price_range', models.CharField(choices=[('$', 'Económico'), ('$$', 'Moderado'), ('$$$', 'Premium'), ('$$$$', 'Lujo')], default='$$', max_length=4)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='venues/covers/')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'venues',
                'ordering': ['-is_verified', '-rating_avg', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VenuePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='venues/photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='venues.venue')),
            ],
            options={
                'db_table': 'venue_photos',
                'ordering': ['order'],
            },
        ),
    ]
